### ISSUE TITLE
Changes to conf.py don't trigger a rebuild

### ISSUE THREAD

**Issue by ojacobson** [wlonk/phix#8]
STR:

1. Start phix and wait for it to build your docs once.
2. Edit `conf.py` and save your changes.
3. Watch the phix logs.

Expected: phix rebuilds the documentation with the new Sphinx configuration.

Actual: phix does not rebuild the documentation, and the configuration changes are not applied until the next action that triggers a rebuild.

**Comment by wlonk** [comment]
Resolved in fe4f3b.
